### ISSUE TITLE
Is all content migrated here already?

### ISSUE THREAD

**Issue by sebastianslutzky** [restfulobjects/restfulobjects.github.io#1]
Hi,

I cannot find the contents of the actual spec in the website. Has the PDF/Word document been migrated to asciidocs already?

Thanks,
Sebastian

**Comment by danhaywood** [comment]
Hi Seb,
You can pull down the .docx or .pdf from [http://restfulobjects.org.](http://restfulobjects.org.)

Funny you should mention having this spec in asciidoc ... been meaning to do this for a long while, and have just started on that; see [https://github.com/restfulobjects/spec](https://github.com/restfulobjects/spec) (work in progress, will take a while...)

Cheers
Dan
